Repository wireapp/wire-ios-transport, pull requests merged in 2022-01, with the labels that each got.

#236 fix: build with Xcode 12.4 SQPIT-781
  Resources/Configurations/version.xcconfig
  azure-pipelines.yml
Labels: DO NOT MERGE

#237 test: dummy PR for release with Xcode 12
  Cartfile
  Resources/Configurations/version.xcconfig
Labels: Fix PR Title 🤦‍♂️

#238 fix: accept json in image content types SQCORE-1226
  Resources/Configurations/version.xcconfig
  Source/Requests/ZMTransportRequest.m
  Tests/Source/TransportSession/ZMTransportSessionTests.m
Labels: patch release
